version: 0.2

phases:
  pre_build:
    commands:
      - aws --version  # This line checks the AWS CLI version
      - if [ $(echo $?) -eq 0 ]; then echo "AWS CLI v2 detected. Skipping upgrade"; else echo "AWS CLI v1 detected or not found. Consider upgrading to v2 for compatibility."; fi  # Conditional check and message
      - echo Logging in to Amazon ECR...
      - aws ecr public login --region ap-south-1
      # ... rest of your pre-build commands ...
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t k8-cicd-ecr-repo .
      - docker tag k8-cicd-ecr-repo:latest public.ecr.aws/h8p8y5w1/k8-cicd-ecr-repo:latest
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push public.ecr.aws/h8p8y5w1/k8-cicd-ecr-repo:latest
      - echo Build completed on `date`
